/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.legolanguage.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.univcotedazur.l3ia.legolanguage.xtext.ide.contentassist.antlr.internal.InternalUduvParser;
import fr.univcotedazur.l3ia.legolanguage.xtext.services.UduvGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class UduvParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UduvGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UduvGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getComparaisonAccess().getAlternatives(), "rule__Comparaison__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getVariableAccess().getAlternatives(), "rule__Variable__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
			builder.put(grammarAccess.getProgramAccess().getGroup_4(), "rule__Program__Group_4__0");
			builder.put(grammarAccess.getProgramAccess().getGroup_4_3(), "rule__Program__Group_4_3__0");
			builder.put(grammarAccess.getWhileLoopAccess().getGroup(), "rule__WhileLoop__Group__0");
			builder.put(grammarAccess.getWhileLoopAccess().getGroup_3(), "rule__WhileLoop__Group_3__0");
			builder.put(grammarAccess.getWhileLoopAccess().getGroup_3_3(), "rule__WhileLoop__Group_3_3__0");
			builder.put(grammarAccess.getSubstarctionAccess().getGroup(), "rule__Substarction__Group__0");
			builder.put(grammarAccess.getGTAccess().getGroup(), "rule__GT__Group__0");
			builder.put(grammarAccess.getAssignementAccess().getGroup(), "rule__Assignement__Group__0");
			builder.put(grammarAccess.getLeIntegerAccess().getGroup(), "rule__LeInteger__Group__0");
			builder.put(grammarAccess.getLeIntegerAccess().getGroup_5(), "rule__LeInteger__Group_5__0");
			builder.put(grammarAccess.getLeStringAccess().getGroup(), "rule__LeString__Group__0");
			builder.put(grammarAccess.getLeStringAccess().getGroup_5(), "rule__LeString__Group_5__0");
			builder.put(grammarAccess.getLTAccess().getGroup(), "rule__LT__Group__0");
			builder.put(grammarAccess.getForLoopAccess().getGroup(), "rule__ForLoop__Group__0");
			builder.put(grammarAccess.getForLoopAccess().getGroup_3(), "rule__ForLoop__Group_3__0");
			builder.put(grammarAccess.getForLoopAccess().getGroup_3_3(), "rule__ForLoop__Group_3_3__0");
			builder.put(grammarAccess.getPrintAccess().getGroup(), "rule__Print__Group__0");
			builder.put(grammarAccess.getVariable_ProxyAccess().getGroup(), "rule__Variable_Proxy__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getProgramAccess().getNameAssignment_2(), "rule__Program__NameAssignment_2");
			builder.put(grammarAccess.getProgramAccess().getStatementAssignment_4_2(), "rule__Program__StatementAssignment_4_2");
			builder.put(grammarAccess.getProgramAccess().getStatementAssignment_4_3_1(), "rule__Program__StatementAssignment_4_3_1");
			builder.put(grammarAccess.getWhileLoopAccess().getNameAssignment_1(), "rule__WhileLoop__NameAssignment_1");
			builder.put(grammarAccess.getWhileLoopAccess().getStatementAssignment_3_2(), "rule__WhileLoop__StatementAssignment_3_2");
			builder.put(grammarAccess.getWhileLoopAccess().getStatementAssignment_3_3_1(), "rule__WhileLoop__StatementAssignment_3_3_1");
			builder.put(grammarAccess.getWhileLoopAccess().getLoopConditionAssignment_5(), "rule__WhileLoop__LoopConditionAssignment_5");
			builder.put(grammarAccess.getSubstarctionAccess().getNameAssignment_1(), "rule__Substarction__NameAssignment_1");
			builder.put(grammarAccess.getSubstarctionAccess().getLeftAssignment_4(), "rule__Substarction__LeftAssignment_4");
			builder.put(grammarAccess.getSubstarctionAccess().getRightAssignment_6(), "rule__Substarction__RightAssignment_6");
			builder.put(grammarAccess.getGTAccess().getNameAssignment_1(), "rule__GT__NameAssignment_1");
			builder.put(grammarAccess.getGTAccess().getLeftAssignment_4(), "rule__GT__LeftAssignment_4");
			builder.put(grammarAccess.getGTAccess().getRightAssignment_6(), "rule__GT__RightAssignment_6");
			builder.put(grammarAccess.getAssignementAccess().getNameAssignment_1(), "rule__Assignement__NameAssignment_1");
			builder.put(grammarAccess.getAssignementAccess().getLeftAssignment_4(), "rule__Assignement__LeftAssignment_4");
			builder.put(grammarAccess.getAssignementAccess().getRightAssignment_6(), "rule__Assignement__RightAssignment_6");
			builder.put(grammarAccess.getLeIntegerAccess().getIsConstAssignment_1(), "rule__LeInteger__IsConstAssignment_1");
			builder.put(grammarAccess.getLeIntegerAccess().getNameAssignment_3(), "rule__LeInteger__NameAssignment_3");
			builder.put(grammarAccess.getLeIntegerAccess().getInitialeValueAssignment_5_1(), "rule__LeInteger__InitialeValueAssignment_5_1");
			builder.put(grammarAccess.getLeStringAccess().getIsConstAssignment_1(), "rule__LeString__IsConstAssignment_1");
			builder.put(grammarAccess.getLeStringAccess().getNameAssignment_3(), "rule__LeString__NameAssignment_3");
			builder.put(grammarAccess.getLeStringAccess().getInitialeValueAssignment_5_1(), "rule__LeString__InitialeValueAssignment_5_1");
			builder.put(grammarAccess.getLTAccess().getNameAssignment_1(), "rule__LT__NameAssignment_1");
			builder.put(grammarAccess.getLTAccess().getLeftAssignment_4(), "rule__LT__LeftAssignment_4");
			builder.put(grammarAccess.getLTAccess().getRightAssignment_6(), "rule__LT__RightAssignment_6");
			builder.put(grammarAccess.getForLoopAccess().getNameAssignment_1(), "rule__ForLoop__NameAssignment_1");
			builder.put(grammarAccess.getForLoopAccess().getStatementAssignment_3_2(), "rule__ForLoop__StatementAssignment_3_2");
			builder.put(grammarAccess.getForLoopAccess().getStatementAssignment_3_3_1(), "rule__ForLoop__StatementAssignment_3_3_1");
			builder.put(grammarAccess.getForLoopAccess().getLoopConditionAssignment_5(), "rule__ForLoop__LoopConditionAssignment_5");
			builder.put(grammarAccess.getPrintAccess().getNameAssignment_2(), "rule__Print__NameAssignment_2");
			builder.put(grammarAccess.getVariable_ProxyAccess().getNameAssignment_1(), "rule__Variable_Proxy__NameAssignment_1");
			builder.put(grammarAccess.getVariable_ProxyAccess().getVariableAssignment_4(), "rule__Variable_Proxy__VariableAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UduvGrammarAccess grammarAccess;

	@Override
	protected InternalUduvParser createParser() {
		InternalUduvParser result = new InternalUduvParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UduvGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UduvGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
