/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.legolanguage.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UduvGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProgramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProgramKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStatementKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cStatementAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cStatementStatementParserRuleCall_4_2_0 = (RuleCall)cStatementAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cStatementAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cStatementStatementParserRuleCall_4_3_1_0 = (RuleCall)cStatementAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Program returns Program:
		//    {Program}
		//    'Program'
		//    name=EString
		//    '{'
		//        ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Program}
		//'Program'
		//name=EString
		//'{'
		//    ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Program}
		public Action getProgramAction_0() { return cProgramAction_0; }
		
		//'Program'
		public Keyword getProgramKeyword_1() { return cProgramKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'statement'
		public Keyword getStatementKeyword_4_0() { return cStatementKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_4_2() { return cStatementAssignment_4_2; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_4_2_0() { return cStatementStatementParserRuleCall_4_2_0; }
		
		//( "," statement+=Statement)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_4_3_1() { return cStatementAssignment_4_3_1; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_4_3_1_0() { return cStatementStatementParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cWhileLoopParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSubstarctionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGTParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAssignementParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cLeIntegerParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cLeStringParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cLTParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cForLoopParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cPrintParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cVariable_ProxyParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		
		//Statement returns Statement:
		//    WhileLoop | Substarction | GT | Assignement | leInteger | leString | LT | ForLoop | Print | Variable_Proxy;
		@Override public ParserRule getRule() { return rule; }
		
		//WhileLoop | Substarction | GT | Assignement | leInteger | leString | LT | ForLoop | Print | Variable_Proxy
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//WhileLoop
		public RuleCall getWhileLoopParserRuleCall_0() { return cWhileLoopParserRuleCall_0; }
		
		//Substarction
		public RuleCall getSubstarctionParserRuleCall_1() { return cSubstarctionParserRuleCall_1; }
		
		//GT
		public RuleCall getGTParserRuleCall_2() { return cGTParserRuleCall_2; }
		
		//Assignement
		public RuleCall getAssignementParserRuleCall_3() { return cAssignementParserRuleCall_3; }
		
		//leInteger
		public RuleCall getLeIntegerParserRuleCall_4() { return cLeIntegerParserRuleCall_4; }
		
		//leString
		public RuleCall getLeStringParserRuleCall_5() { return cLeStringParserRuleCall_5; }
		
		//LT
		public RuleCall getLTParserRuleCall_6() { return cLTParserRuleCall_6; }
		
		//ForLoop
		public RuleCall getForLoopParserRuleCall_7() { return cForLoopParserRuleCall_7; }
		
		//Print
		public RuleCall getPrintParserRuleCall_8() { return cPrintParserRuleCall_8; }
		
		//Variable_Proxy
		public RuleCall getVariable_ProxyParserRuleCall_9() { return cVariable_ProxyParserRuleCall_9; }
	}
	public class ComparaisonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Comparaison");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGTParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLTParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Comparaison returns Comparaison:
		//    GT | LT;
		@Override public ParserRule getRule() { return rule; }
		
		//GT | LT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GT
		public RuleCall getGTParserRuleCall_0() { return cGTParserRuleCall_0; }
		
		//LT
		public RuleCall getLTParserRuleCall_1() { return cLTParserRuleCall_1; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSubstarctionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGTParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAssignementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLTParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPrintParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cVariable_ProxyParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Expression returns Expression:
		//    Substarction | GT | Assignement | LT | Print | Variable_Proxy;
		@Override public ParserRule getRule() { return rule; }
		
		//Substarction | GT | Assignement | LT | Print | Variable_Proxy
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Substarction
		public RuleCall getSubstarctionParserRuleCall_0() { return cSubstarctionParserRuleCall_0; }
		
		//GT
		public RuleCall getGTParserRuleCall_1() { return cGTParserRuleCall_1; }
		
		//Assignement
		public RuleCall getAssignementParserRuleCall_2() { return cAssignementParserRuleCall_2; }
		
		//LT
		public RuleCall getLTParserRuleCall_3() { return cLTParserRuleCall_3; }
		
		//Print
		public RuleCall getPrintParserRuleCall_4() { return cPrintParserRuleCall_4; }
		
		//Variable_Proxy
		public RuleCall getVariable_ProxyParserRuleCall_5() { return cVariable_ProxyParserRuleCall_5; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Variable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLeIntegerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLeStringParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Variable returns Variable:
		//    leInteger | leString;
		@Override public ParserRule getRule() { return rule; }
		
		//leInteger | leString
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//leInteger
		public RuleCall getLeIntegerParserRuleCall_0() { return cLeIntegerParserRuleCall_0; }
		
		//leString
		public RuleCall getLeStringParserRuleCall_1() { return cLeStringParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class WhileLoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.WhileLoop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWhileLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStatementKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cStatementAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cStatementStatementParserRuleCall_3_2_0 = (RuleCall)cStatementAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cStatementAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cStatementStatementParserRuleCall_3_3_1_0 = (RuleCall)cStatementAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cLoopConditionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLoopConditionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLoopConditionComparaisonParserRuleCall_5_0 = (RuleCall)cLoopConditionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//WhileLoop returns WhileLoop:
		//    'WhileLoop'
		//    name=EString
		//    '{'
		//        ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		//        'loopCondition' loopCondition=Comparaison
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'WhileLoop'
		//name=EString
		//'{'
		//    ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		//    'loopCondition' loopCondition=Comparaison
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'WhileLoop'
		public Keyword getWhileLoopKeyword_0() { return cWhileLoopKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'statement'
		public Keyword getStatementKeyword_3_0() { return cStatementKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_3_2() { return cStatementAssignment_3_2; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_3_2_0() { return cStatementStatementParserRuleCall_3_2_0; }
		
		//( "," statement+=Statement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_3_3_1() { return cStatementAssignment_3_3_1; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_3_3_1_0() { return cStatementStatementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'loopCondition'
		public Keyword getLoopConditionKeyword_4() { return cLoopConditionKeyword_4; }
		
		//loopCondition=Comparaison
		public Assignment getLoopConditionAssignment_5() { return cLoopConditionAssignment_5; }
		
		//Comparaison
		public RuleCall getLoopConditionComparaisonParserRuleCall_5_0() { return cLoopConditionComparaisonParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SubstarctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Substarction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubstarctionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLeftAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLeftExpressionParserRuleCall_4_0 = (RuleCall)cLeftAssignment_4.eContents().get(0);
		private final Keyword cRightKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRightAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRightExpressionParserRuleCall_6_0 = (RuleCall)cRightAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Substarction returns Substarction:
		//    'Substarction'
		//    name=EString
		//    '{'
		//        'left' left=Expression
		//        'right' right=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Substarction'
		//name=EString
		//'{'
		//    'left' left=Expression
		//    'right' right=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Substarction'
		public Keyword getSubstarctionKeyword_0() { return cSubstarctionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'left'
		public Keyword getLeftKeyword_3() { return cLeftKeyword_3; }
		
		//left=Expression
		public Assignment getLeftAssignment_4() { return cLeftAssignment_4; }
		
		//Expression
		public RuleCall getLeftExpressionParserRuleCall_4_0() { return cLeftExpressionParserRuleCall_4_0; }
		
		//'right'
		public Keyword getRightKeyword_5() { return cRightKeyword_5; }
		
		//right=Expression
		public Assignment getRightAssignment_6() { return cRightAssignment_6; }
		
		//Expression
		public RuleCall getRightExpressionParserRuleCall_6_0() { return cRightExpressionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class GTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.GT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLeftAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLeftExpressionParserRuleCall_4_0 = (RuleCall)cLeftAssignment_4.eContents().get(0);
		private final Keyword cRightKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRightAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRightExpressionParserRuleCall_6_0 = (RuleCall)cRightAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//GT returns GT:
		//    'GT'
		//    name=EString
		//    '{'
		//        'left' left=Expression
		//        'right' right=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GT'
		//name=EString
		//'{'
		//    'left' left=Expression
		//    'right' right=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'GT'
		public Keyword getGTKeyword_0() { return cGTKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'left'
		public Keyword getLeftKeyword_3() { return cLeftKeyword_3; }
		
		//left=Expression
		public Assignment getLeftAssignment_4() { return cLeftAssignment_4; }
		
		//Expression
		public RuleCall getLeftExpressionParserRuleCall_4_0() { return cLeftExpressionParserRuleCall_4_0; }
		
		//'right'
		public Keyword getRightKeyword_5() { return cRightKeyword_5; }
		
		//right=Expression
		public Assignment getRightAssignment_6() { return cRightAssignment_6; }
		
		//Expression
		public RuleCall getRightExpressionParserRuleCall_6_0() { return cRightExpressionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AssignementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Assignement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssignementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLeftAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLeftExpressionParserRuleCall_4_0 = (RuleCall)cLeftAssignment_4.eContents().get(0);
		private final Keyword cRightKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRightAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRightExpressionParserRuleCall_6_0 = (RuleCall)cRightAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Assignement returns Assignement:
		//    'Assignement'
		//    name=EString
		//    '{'
		//        'left' left=Expression
		//        'right' right=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Assignement'
		//name=EString
		//'{'
		//    'left' left=Expression
		//    'right' right=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Assignement'
		public Keyword getAssignementKeyword_0() { return cAssignementKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'left'
		public Keyword getLeftKeyword_3() { return cLeftKeyword_3; }
		
		//left=Expression
		public Assignment getLeftAssignment_4() { return cLeftAssignment_4; }
		
		//Expression
		public RuleCall getLeftExpressionParserRuleCall_4_0() { return cLeftExpressionParserRuleCall_4_0; }
		
		//'right'
		public Keyword getRightKeyword_5() { return cRightKeyword_5; }
		
		//right=Expression
		public Assignment getRightAssignment_6() { return cRightAssignment_6; }
		
		//Expression
		public RuleCall getRightExpressionParserRuleCall_6_0() { return cRightExpressionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class LeIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.leInteger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLeIntegerAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIsConstAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsConstIsConstKeyword_1_0 = (Keyword)cIsConstAssignment_1.eContents().get(0);
		private final Keyword cLeIntegerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInitialeValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInitialeValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInitialeValueEIntParserRuleCall_5_1_0 = (RuleCall)cInitialeValueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//leInteger returns leInteger:
		//    {leInteger}
		//    (isConst?='isConst')?
		//    'leInteger'
		//    name=EString
		//    '{'
		//        ('initialeValue' initialeValue=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{leInteger}
		//(isConst?='isConst')?
		//'leInteger'
		//name=EString
		//'{'
		//    ('initialeValue' initialeValue=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{leInteger}
		public Action getLeIntegerAction_0() { return cLeIntegerAction_0; }
		
		//(isConst?='isConst')?
		public Assignment getIsConstAssignment_1() { return cIsConstAssignment_1; }
		
		//'isConst'
		public Keyword getIsConstIsConstKeyword_1_0() { return cIsConstIsConstKeyword_1_0; }
		
		//'leInteger'
		public Keyword getLeIntegerKeyword_2() { return cLeIntegerKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('initialeValue' initialeValue=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'initialeValue'
		public Keyword getInitialeValueKeyword_5_0() { return cInitialeValueKeyword_5_0; }
		
		//initialeValue=EInt
		public Assignment getInitialeValueAssignment_5_1() { return cInitialeValueAssignment_5_1; }
		
		//EInt
		public RuleCall getInitialeValueEIntParserRuleCall_5_1_0() { return cInitialeValueEIntParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class LeStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.leString");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLeStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIsConstAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsConstIsConstKeyword_1_0 = (Keyword)cIsConstAssignment_1.eContents().get(0);
		private final Keyword cLeStringKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInitialeValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInitialeValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInitialeValueEStringParserRuleCall_5_1_0 = (RuleCall)cInitialeValueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//leString returns leString:
		//    {leString}
		//    (isConst?='isConst')?
		//    'leString'
		//    name=EString
		//    '{'
		//        ('initialeValue' initialeValue=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{leString}
		//(isConst?='isConst')?
		//'leString'
		//name=EString
		//'{'
		//    ('initialeValue' initialeValue=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{leString}
		public Action getLeStringAction_0() { return cLeStringAction_0; }
		
		//(isConst?='isConst')?
		public Assignment getIsConstAssignment_1() { return cIsConstAssignment_1; }
		
		//'isConst'
		public Keyword getIsConstIsConstKeyword_1_0() { return cIsConstIsConstKeyword_1_0; }
		
		//'leString'
		public Keyword getLeStringKeyword_2() { return cLeStringKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('initialeValue' initialeValue=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'initialeValue'
		public Keyword getInitialeValueKeyword_5_0() { return cInitialeValueKeyword_5_0; }
		
		//initialeValue=EString
		public Assignment getInitialeValueAssignment_5_1() { return cInitialeValueAssignment_5_1; }
		
		//EString
		public RuleCall getInitialeValueEStringParserRuleCall_5_1_0() { return cInitialeValueEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class LTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.LT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLeftAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLeftExpressionParserRuleCall_4_0 = (RuleCall)cLeftAssignment_4.eContents().get(0);
		private final Keyword cRightKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRightAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRightExpressionParserRuleCall_6_0 = (RuleCall)cRightAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//LT returns LT:
		//    'LT'
		//    name=EString
		//    '{'
		//        'left' left=Expression
		//        'right' right=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'LT'
		//name=EString
		//'{'
		//    'left' left=Expression
		//    'right' right=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'LT'
		public Keyword getLTKeyword_0() { return cLTKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'left'
		public Keyword getLeftKeyword_3() { return cLeftKeyword_3; }
		
		//left=Expression
		public Assignment getLeftAssignment_4() { return cLeftAssignment_4; }
		
		//Expression
		public RuleCall getLeftExpressionParserRuleCall_4_0() { return cLeftExpressionParserRuleCall_4_0; }
		
		//'right'
		public Keyword getRightKeyword_5() { return cRightKeyword_5; }
		
		//right=Expression
		public Assignment getRightAssignment_6() { return cRightAssignment_6; }
		
		//Expression
		public RuleCall getRightExpressionParserRuleCall_6_0() { return cRightExpressionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ForLoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.ForLoop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStatementKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cStatementAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cStatementStatementParserRuleCall_3_2_0 = (RuleCall)cStatementAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cStatementAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cStatementStatementParserRuleCall_3_3_1_0 = (RuleCall)cStatementAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cLoopConditionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLoopConditionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLoopConditionComparaisonParserRuleCall_5_0 = (RuleCall)cLoopConditionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ForLoop returns ForLoop:
		//    'ForLoop'
		//    name=EString
		//    '{'
		//        ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		//        'loopCondition' loopCondition=Comparaison
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ForLoop'
		//name=EString
		//'{'
		//    ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		//    'loopCondition' loopCondition=Comparaison
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ForLoop'
		public Keyword getForLoopKeyword_0() { return cForLoopKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'statement'
		public Keyword getStatementKeyword_3_0() { return cStatementKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_3_2() { return cStatementAssignment_3_2; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_3_2_0() { return cStatementStatementParserRuleCall_3_2_0; }
		
		//( "," statement+=Statement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_3_3_1() { return cStatementAssignment_3_3_1; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_3_3_1_0() { return cStatementStatementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'loopCondition'
		public Keyword getLoopConditionKeyword_4() { return cLoopConditionKeyword_4; }
		
		//loopCondition=Comparaison
		public Assignment getLoopConditionAssignment_5() { return cLoopConditionAssignment_5; }
		
		//Comparaison
		public RuleCall getLoopConditionComparaisonParserRuleCall_5_0() { return cLoopConditionComparaisonParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPrintAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPrintKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Print returns Print:
		//    {Print}
		//    'Print'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Print}
		//'Print'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Print}
		public Action getPrintAction_0() { return cPrintAction_0; }
		
		//'Print'
		public Keyword getPrintKeyword_1() { return cPrintKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class Variable_ProxyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.Variable_Proxy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVariable_ProxyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVariableKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVariableAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cVariableVariableCrossReference_4_0 = (CrossReference)cVariableAssignment_4.eContents().get(0);
		private final RuleCall cVariableVariableEStringParserRuleCall_4_0_1 = (RuleCall)cVariableVariableCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Variable_Proxy returns Variable_Proxy:
		//    'Variable_Proxy'
		//    name=EString
		//    '{'
		//        'Variable' Variable=[Variable|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Variable_Proxy'
		//name=EString
		//'{'
		//    'Variable' Variable=[Variable|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Variable_Proxy'
		public Keyword getVariable_ProxyKeyword_0() { return cVariable_ProxyKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Variable'
		public Keyword getVariableKeyword_3() { return cVariableKeyword_3; }
		
		//Variable=[Variable|EString]
		public Assignment getVariableAssignment_4() { return cVariableAssignment_4; }
		
		//[Variable|EString]
		public CrossReference getVariableVariableCrossReference_4_0() { return cVariableVariableCrossReference_4_0; }
		
		//EString
		public RuleCall getVariableVariableEStringParserRuleCall_4_0_1() { return cVariableVariableEStringParserRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.univcotedazur.l3ia.legolanguage.xtext.Uduv.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final ProgramElements pProgram;
	private final StatementElements pStatement;
	private final ComparaisonElements pComparaison;
	private final ExpressionElements pExpression;
	private final VariableElements pVariable;
	private final EStringElements pEString;
	private final WhileLoopElements pWhileLoop;
	private final SubstarctionElements pSubstarction;
	private final GTElements pGT;
	private final AssignementElements pAssignement;
	private final LeIntegerElements pLeInteger;
	private final LeStringElements pLeString;
	private final LTElements pLT;
	private final ForLoopElements pForLoop;
	private final PrintElements pPrint;
	private final Variable_ProxyElements pVariable_Proxy;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UduvGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pStatement = new StatementElements();
		this.pComparaison = new ComparaisonElements();
		this.pExpression = new ExpressionElements();
		this.pVariable = new VariableElements();
		this.pEString = new EStringElements();
		this.pWhileLoop = new WhileLoopElements();
		this.pSubstarction = new SubstarctionElements();
		this.pGT = new GTElements();
		this.pAssignement = new AssignementElements();
		this.pLeInteger = new LeIntegerElements();
		this.pLeString = new LeStringElements();
		this.pLT = new LTElements();
		this.pForLoop = new ForLoopElements();
		this.pPrint = new PrintElements();
		this.pVariable_Proxy = new Variable_ProxyElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.univcotedazur.l3ia.legolanguage.xtext.Uduv".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program returns Program:
	//    {Program}
	//    'Program'
	//    name=EString
	//    '{'
	//        ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
	//    '}';
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Statement returns Statement:
	//    WhileLoop | Substarction | GT | Assignement | leInteger | leString | LT | ForLoop | Print | Variable_Proxy;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Comparaison returns Comparaison:
	//    GT | LT;
	public ComparaisonElements getComparaisonAccess() {
		return pComparaison;
	}
	
	public ParserRule getComparaisonRule() {
		return getComparaisonAccess().getRule();
	}
	
	//Expression returns Expression:
	//    Substarction | GT | Assignement | LT | Print | Variable_Proxy;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Variable returns Variable:
	//    leInteger | leString;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//WhileLoop returns WhileLoop:
	//    'WhileLoop'
	//    name=EString
	//    '{'
	//        ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
	//        'loopCondition' loopCondition=Comparaison
	//    '}';
	public WhileLoopElements getWhileLoopAccess() {
		return pWhileLoop;
	}
	
	public ParserRule getWhileLoopRule() {
		return getWhileLoopAccess().getRule();
	}
	
	//Substarction returns Substarction:
	//    'Substarction'
	//    name=EString
	//    '{'
	//        'left' left=Expression
	//        'right' right=Expression
	//    '}';
	public SubstarctionElements getSubstarctionAccess() {
		return pSubstarction;
	}
	
	public ParserRule getSubstarctionRule() {
		return getSubstarctionAccess().getRule();
	}
	
	//GT returns GT:
	//    'GT'
	//    name=EString
	//    '{'
	//        'left' left=Expression
	//        'right' right=Expression
	//    '}';
	public GTElements getGTAccess() {
		return pGT;
	}
	
	public ParserRule getGTRule() {
		return getGTAccess().getRule();
	}
	
	//Assignement returns Assignement:
	//    'Assignement'
	//    name=EString
	//    '{'
	//        'left' left=Expression
	//        'right' right=Expression
	//    '}';
	public AssignementElements getAssignementAccess() {
		return pAssignement;
	}
	
	public ParserRule getAssignementRule() {
		return getAssignementAccess().getRule();
	}
	
	//leInteger returns leInteger:
	//    {leInteger}
	//    (isConst?='isConst')?
	//    'leInteger'
	//    name=EString
	//    '{'
	//        ('initialeValue' initialeValue=EInt)?
	//    '}';
	public LeIntegerElements getLeIntegerAccess() {
		return pLeInteger;
	}
	
	public ParserRule getLeIntegerRule() {
		return getLeIntegerAccess().getRule();
	}
	
	//leString returns leString:
	//    {leString}
	//    (isConst?='isConst')?
	//    'leString'
	//    name=EString
	//    '{'
	//        ('initialeValue' initialeValue=EString)?
	//    '}';
	public LeStringElements getLeStringAccess() {
		return pLeString;
	}
	
	public ParserRule getLeStringRule() {
		return getLeStringAccess().getRule();
	}
	
	//LT returns LT:
	//    'LT'
	//    name=EString
	//    '{'
	//        'left' left=Expression
	//        'right' right=Expression
	//    '}';
	public LTElements getLTAccess() {
		return pLT;
	}
	
	public ParserRule getLTRule() {
		return getLTAccess().getRule();
	}
	
	//ForLoop returns ForLoop:
	//    'ForLoop'
	//    name=EString
	//    '{'
	//        ('statement' '{' statement+=Statement ( "," statement+=Statement)* '}' )?
	//        'loopCondition' loopCondition=Comparaison
	//    '}';
	public ForLoopElements getForLoopAccess() {
		return pForLoop;
	}
	
	public ParserRule getForLoopRule() {
		return getForLoopAccess().getRule();
	}
	
	//Print returns Print:
	//    {Print}
	//    'Print'
	//    name=EString;
	public PrintElements getPrintAccess() {
		return pPrint;
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}
	
	//Variable_Proxy returns Variable_Proxy:
	//    'Variable_Proxy'
	//    name=EString
	//    '{'
	//        'Variable' Variable=[Variable|EString]
	//    '}';
	public Variable_ProxyElements getVariable_ProxyAccess() {
		return pVariable_Proxy;
	}
	
	public ParserRule getVariable_ProxyRule() {
		return getVariable_ProxyAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
