/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.legolanguage.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UduvStandaloneSetup extends UduvStandaloneSetupGenerated {

	public static void doSetup() {
		new UduvStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
