/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.l3ia.legolanguage.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UduvUiModule extends AbstractUduvUiModule {

	public UduvUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
